[project]
name = "ai-engineer-labs"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Arthur Masera Berquo", email = "e-aberquo@tap.pt" }
]
requires-python = ">=3.12"
dependencies = [
    "anthropic>=1.4.0",
    "duckdb>=1.5.5",
    "httpx>=0.28.1",
    "openai>=3.11.0",
    "pandas>=3.0.5",
    "python-dotenv>=1.2.3",
    "pyyaml>=6.0.3",
]

[project.scripts]
ai-engineer-labs = "ai_engineer_labs:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
